# For Nuxt app
# @memo: copy everything to /usr/src/app

FROM node:20-slim
LABEL maintainer="B24Sdk <github.com/bitrix24>"

WORKDIR /usr/src/app

RUN corepack enable

COPY .npmrc package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install

COPY . ./

ENV PORT=3000
ENV HOST=0.0.0.0

EXPOSE 3000

CMD ["pnpm", "run", "dev"]
