# For Nuxt app
# @memo: copy everything to /usr/src/app

FROM node:20-slim
LABEL maintainer="B24Sdk <github.com/bitrix24>"

RUN apt-get update && apt-get install -y openssl

WORKDIR /usr/src/app

RUN corepack enable

COPY .npmrc package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY prisma ./prisma/
RUN pnpm install
RUN pnpm run prisma:generate

COPY . ./

EXPOSE 3000

CMD ["pnpm", "run", "dev"]
