# For Nuxt app
# @memo: copy everything to /usr/src/app

FROM node:20-alpine AS builder
LABEL maintainer="B24Sdk <github.com/bitrix24>"

# RUN apt-get update && apt-get install -y openssl

WORKDIR /usr/src/app

RUN corepack enable

COPY .npmrc package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY prisma ./prisma/
RUN pnpm install
RUN pnpm run prisma:generate

COPY . ./

RUN pnpm run build

FROM node:20-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/.output ./
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/prisma ./prisma

EXPOSE 80

# CMD ["node", "/usr/src/app/server/index.mjs"]
