services:
  frontend:
    container_name: frontend
    depends_on:
      - chrome
      - server
    build:
      context: ./frontend
      dockerfile: Dockerfile_prod
    expose:
      - '80'
    volumes:
      - ./frontend:/usr/src/app
      - ./logs:/tmp
      - /usr/src/app/node_modules
    env_file: .env.prod
    networks:
      - internal-net
      - proxy-net
    restart: always

  chrome:
    container_name: chrome
    build:
      context: ./chrome
      dockerfile: Dockerfile
    ports:
      - '9222:9222'
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:9222/json/version || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - internal-net
    # @todo fix this
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

  server:
    container_name: server
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-net

  letsencrypt:
    container_name: letsencrypt
    image: nginxproxy/acme-companion
    volumes_from:
      - server
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - server
    networks:
      - proxy-net

networks:
  proxy-net:
    driver: bridge
  internal-net:
    driver: bridge
