services:
  frontend:
    container_name: prod-frontend
    depends_on:
      - chrome
    build:
      context: ./frontend
      dockerfile: Dockerfile_prod
    expose:
      - '80'
    volumes:
      - ./logs:/tmp
    env_file: .env.prod
    networks:
      - internal-net
      - proxy-net
    restart: always

  chrome:
    container_name: prod-chrome
    build:
      context: ./chrome
      dockerfile: Dockerfile_prod
    ports:
      - '9222:9222'
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:9222/json/version || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - internal-net
    # @todo fix this
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

networks:
  proxy-net:
    driver: bridge
    external: true
  internal-net:
    driver: bridge
