services:
  chrome:
    container_name: prod-chrome
    build:
      context: ./chrome
      dockerfile: Dockerfile_prod
    deploy:
      resources:
        limits:
          cpus: '0.8' # CPU limit
          memory: 1G # Max memory
    shm_size: 256mb
    ports:
      - '9223:9223'
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://0.0.0.0:9223/json/version || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - internal-net
    restart: always

  rabbitmq:
    container_name: prod-rabbitmq
    image: rabbitmq:4.1.0-management-alpine
    deploy:
      resources:
        limits:
          cpus: '0.5' # CPU limit
          memory: 512M # Max memory
    ports:
      - '5673:5673' # need sync with RABBITMQ_NODE_PORT
      - '15673:15672' # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file: .env.prod
    environment:
      VIRTUAL_PORT: 15672
      VIRTUAL_HOST: "rbt.${VIRTUAL_HOST}"
      LETSENCRYPT_HOST: "rbt.${LETSENCRYPT_HOST}"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - internal-net
      - proxy-net
    restart: always

  db:
    image: postgres:17-alpine
    container_name: prod-db
    deploy:
      resources:
        limits:
          cpus: '1.2' # CPU limit
          memory: 2G # Max memory
        reservations:
          cpus: '0.5' # Guaranteed CPUs
          memory: 1G # Minimum memory
    shm_size: 384mb
    ports:
      - "5433:5433" # need sync with PGPORT
    env_file: .env.prod
    networks:
      - internal-net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5
    restart: always

  frontend:
    container_name: prod-frontend
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    build:
      context: ./frontend
      dockerfile: Dockerfile_prod
    deploy:
      resources:
        limits:
          cpus: '1.0' # CPU limit
          memory: 768M # Max memory
        reservations:
          cpus: '1.0' # Guaranteed CPUs
          memory: 768M # Minimum memory
    expose:
      - '80'
#    volumes:
#      - ./frontend:/usr/src/app
#      - /usr/src/app/node_modules
#      - /usr/src/app/generated
    env_file: .env.prod
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${PGPORT}/${POSTGRES_DB}?schema=public"
      NUXT_PUBLIC_APP_URL: "https://${VIRTUAL_HOST}"
      NUXT_RABBITMQ_URL: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:${RABBITMQ_NODE_PORT}"
    networks:
      - internal-net
      - proxy-net
    restart: always

  consumer-nodejs-pdf-from-html:
    depends_on:
      chrome:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    build:
      context: ./consumers/activities/nodejs-pdf-from-html
      dockerfile: Dockerfile_prod
    deploy:
      resources:
        limits:
          cpus: '0.3' # CPU limit
          memory: 384M # Max memory
    volumes:
      - ./consumers/activities/nodejs-pdf-from-html:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/generated
    env_file: .env.prod
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${PGPORT}/${POSTGRES_DB}?schema=public"
      NUXT_PUBLIC_APP_URL: "https://${VIRTUAL_HOST}"
      NUXT_RABBITMQ_URL: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:${RABBITMQ_NODE_PORT}"
    networks:
      - internal-net
    restart: always

  consumer-php-crm-entity-task-calc:
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    build:
      context: ./consumers/activities/php-crm-entity-task-calc
      dockerfile: Dockerfile_dev
    deploy:
      resources:
        limits:
          cpus: '0.5' # CPU limit
          memory: 384M # Max memory
    volumes:
      - ./consumers/activities/php-crm-entity-task-calc:/usr/src/app
      - /usr/src/app/vendor
    env_file: .env.dev
    environment:
      PHP_MEMORY_LIMIT: 256M
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${PGPORT}/${POSTGRES_DB}?schema=public"
      NUXT_PUBLIC_APP_URL: "https://${VIRTUAL_HOST}"
      NUXT_RABBITMQ_URL: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:${RABBITMQ_NODE_PORT}"
    networks:
      - internal-net
    restart: always

networks:
  proxy-net:
    driver: bridge
    external: true
  internal-net:
    driver: bridge

volumes:
  rabbitmq_data:
  postgres_data:
