services:
  server:
    image: nginxproxy/nginx-proxy
    container_name: server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: '1.0'

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: letsencrypt
    volumes_from:
      - server
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - server
    networks:
      - proxy-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: '1.0'

volumes:
  conf:
  vhost:
  dhparam:
  certs:
  html:
  acme:

networks:
  proxy-net:
    driver: bridge
    external: true
