services:
  frontend:
    container_name: dev-frontend
    depends_on:
      - chrome
    build:
      context: ./frontend
      dockerfile: Dockerfile_dev
    expose:
      - '3000'
    volumes:
      - ./frontend:/usr/src/app
      - ./logs:/tmp
      - /usr/src/app/node_modules
    env_file: .env.dev
    networks:
      - internal-net
      - proxy-net
    restart: always

  chrome:
    container_name: dev-chrome
    build:
      context: ./chrome
      dockerfile: Dockerfile_dev
    ports:
      - '9223:9223'
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:9223/json/version || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - internal-net
    # @todo fix this
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

networks:
  proxy-net:
    driver: bridge
    external: true
  internal-net:
    driver: bridge
