services:
  frontend:
    container_name: frontend
    depends_on:
      - chrome
    build: ./frontend
    expose:
      - '3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./logs:/tmp
    env_file: .env.dev
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - VITE_APP_INTERNAL_URL=http://frontend:3000
      - VITE_CHROME_WS_URL_2=ws://chrome:3000
      - VITE_CHROME_WS_URL=ws://chrome:9222/devtools/browser
    networks:
      - inner
    restart: always

  chrome:
    image: zenika/alpine-chrome
    container_name: chrome
    ports:
      - '9222:9222'
    command: >
      --no-sandbox
      --headless
      --disable-gpu
      --disable-dev-shm-usage
      --remote-debugging-address=0.0.0.0
      --remote-debugging-port=9222
      --disable-web-security
      --ignore-certificate-errors
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:9222/json/version || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - inner

  server:
    container_name: server
    labels:
      app__bp_activity: '@bitrix24/b24ui-playground-nuxt-starter-bp-activity'
    depends_on:
      - frontend
    build: ./nginx
    volumes:
      - ./certs:/etc/nginx/certs
      - /tmp/letsencrypt/www:/tmp/letsencrypt/www
    env_file: .env.dev
    links:
      - frontend:frontend
    ports:
      - '80:80'
      - '443:443'
    networks:
      - inner
    restart: unless-stopped

  letsencrypt:
    container_name: server-letsencrypt
    depends_on:
      - server
      - frontend
    build: ./letsencrypt
    links:
     - server
    volumes:
      - ./certs:/etc/nginx/certs
      # - ./logs/letsencrypt:/var/log/letsencrypt
      - /var/log/letsencrypt/:/var/log/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /tmp/letsencrypt/www:/tmp/letsencrypt/www
    env_file: .env.dev
    environment:
      # - DRY_RUN=Y
      - SERVER_CONTAINER_LABEL=app__bp_activity
      - WEBROOT_PATH=/tmp/letsencrypt/www
      - CERTS_PATH=/etc/nginx/certs
      - CHECK_FREQ=7
    networks:
      - inner
    restart: unless-stopped

networks:
  inner:
    driver: bridge
