services:
  server:
    container_name: server
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: '1.0'

  letsencrypt:
    container_name: letsencrypt
    image: nginxproxy/acme-companion
    volumes_from:
      - server
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - server
    networks:
      - proxy-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: '1.0'

networks:
  proxy-net:
    driver: bridge
    external: true
