# For consumer
# @memo: copy everything to /usr/src/app

FROM php:8.3-cli
LABEL maintainer="B24Sdk <github.com/bitrix24>"

RUN apt-get update && apt-get install -y \
    libzip-dev \
    zip \
    librabbitmq-dev \
    libssl-dev \
    libicu-dev \
    libpq-dev \
    && docker-php-ext-install \
      zip \
      intl \
      bcmath \
      sockets \
      pdo_pgsql \
      pgsql \
    && pecl install amqp \
    && docker-php-ext-enable amqp

RUN curl -sS https://getcomposer.org/installer | php -- \
    --install-dir=/usr/local/bin \
    --filename=composer

WORKDIR /usr/src/app

COPY . .

RUN composer install --no-dev --optimize-autoloader

CMD ["php", "/usr/src/app/consumer.php"]
