# @memo We close our eyes to the mistakes of D-BUS
FROM zenika/alpine-chrome
LABEL maintainer="B24Sdk <github.com/bitrix24>"

USER root

# Install dependencies: Nginx + Noto fonts (support the ruble symbol)
RUN apk add --no-cache \
    nginx \
    font-noto \
    font-noto-extra \
    fontconfig && \
    # Nginx
    mkdir -p /var/lib/nginx/tmp && \
    # Chrome
    chown -R chrome:chrome /var/lib/nginx /run /var/log/nginx && \
    # Clearing cache
    rm -rf /var/cache/apk/* && \
    # Updating font cache
    fc-cache -f -v

COPY nginx_dev.conf /etc/nginx/nginx.conf
COPY entrypoint.sh /

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
