# @memo We close our eyes to the mistakes of D-BUS
FROM zenika/alpine-chrome

LABEL maintainer="B24Sdk <github.com/bitrix24>"

USER root
RUN apk add --no-cache \
    nginx && \
    # Nginx
    mkdir -p /var/lib/nginx/tmp && \
    # Chrome
    chown -R chrome:chrome /var/lib/nginx /run /var/log/nginx && \
    rm -rf /var/cache/apk/*

COPY nginx_dev.conf /etc/nginx/nginx.conf
COPY entrypoint.sh /

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
